version: "3.7"
services:
  front:
    build:
      context: front/
      dockerfile: Dockerfile
      args: 
        - ENV_FILE=./local.env
    ports:
      - 7000:80
    environment:
      - NODE_ENV=production
  back:
    init: true
    build:
      context: back/
      dockerfile: Dockerfile
    ports:
      - 7001:3000
    environment:
      - NODE_ENV=production
      - PGHOST=database
      - PGPORT= 5432
      - PGUSER=test-user
      - PGPASSWORD=test-password
      - PGDATABASE=test
  database:
    image: postgres:11.7-alpine
    expose: 
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=test-user
      - POSTGRES_PASSWORD=test-password
      - POSTGRES_DB=test
    volumes: 
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d